### ISSUE TITLE
typo in AppDeployToolkitConfig.xml procced should be proceed

### ISSUE THREAD

**Issue by neo42mgn** [neo42-GmbH/PSAppDeployToolKitExtensions#1166] opened 2024-11-21 14:22 UTC
### Confirmation

- [X] My issue is not related to the behaviour of a package or product provided by neo42
- [X] I understand that issues created in this repository are not subject to any support agreements made with neo42

### Release

47

**Comment by neo42JBR** [comment] 2024-11-28 09:11
duplicate of #1172

**Closed as completed by neo42JBR** 2024-11-28 09:11 UTC
Labels: Bug
